name: Publish to Zenodo

on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main
              with:
                  logger: pretty
                  log-directives: nix_installer=trace
                  backtrace: full

            - name: Nix cache
              uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Run command in flake environment
              env:
                  ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
              run: |
                  export ZENODO_TOKEN="ZENODO_TOKEN" && nix develop . --accept-flake-config --impure --command bash src/upload_index.sh
